modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "rockettrades"
version = "${version}"
displayName = "Rocket Trades"
authors = "JungleHornet"
description = '''
Custom villager trades
'''
#logoFile = ""

[[dependencies.rockettrades]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rockettrades]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rockettrades]]
modId = "architectury"
type = "required"
versionRange = "[18.0.6,)"
ordering = "AFTER"
side = "BOTH"
